### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by oritpersik** [stacksight/wordpress#12]
[Mon Jul 11 15:00:23 2016] [error] [client 198.143.43.17] PHP Warning:  array_keys() expects parameter 1 to be array, null given in /var/www/istolar.com/wordpress/wp-content/plugins/stacksight/wp-stacksight.php on line 1001, referer: http://www.istolar.com/wp-admin/admin.php?page=stacksight`

**Comment by igor-lemon** [comment]
Done
