### ISSUE TITLE
Path for php-wordpress in incorect

### ISSUE THREAD

**Issue by hermanlinnovate** [stacksight/wordpress#4]

**Comment by hermanlinnovate** [comment]
Lior kisos is aware of issue- happen on local hosting

**Comment by igor-lemon** [comment]
What is "php-wordpress" path? I don't understand you.

**Comment by hermanlinnovate** [comment]
Very simple:

You know how WordPress create a php path (code) i should inset in my
wp-config?
So that line is broken, the only way to run stacksight correct is to copy
the php output line that shows up in staksight itself. so path should be
correlated...

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=herman@linnovate.net&idSignature=22

On Thu, Feb 11, 2016 at 10:36 AM, Igor Kozlovsky notifications@github.com
wrote:

> What is "php-wordpress" path? I don't understand you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stacksight/wordpress/issues/4#issuecomment-182765050.

## 

Lior Herman
herman@linnovate.net
Skype: lior.herman1
M: +972-52-629-8889
